[package]
name = "people-in-space"
version = "0.1.1"
authors = ["TheSpiffiest"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
tokio = { version = "1.9", features = ["full"] }
